scss:
  enabled: false
sass-lint:
  enabled: false
ruby:
  enabled: true
  config_file: .rubocop.yml
javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore
