scss:
  enabled: false
jshint:
  enabled: false
rubocop:
  config_file: .rubocop.yml
  version: 0.71.0
eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore
  version: 5.16.0
