# encoding: utf-8
gem 'minitest', '5.0.3'
require 'minitest'
require 'rake/testtask'

Rake::TestTask.new do |t|
  gem_spec  = Gem.loaded_specs.fetch('minitest')
  t.libs << "test"
  t.pattern = "spec/**/*_spec.rb"
end

