#!/usr/bin/env ruby
# encoding: utf-8
require 'open3'

module Workman
  module Commands
    class Echo
      COMMAND = "echo"

      def run
        stdin, stdout, stderr = Open3.popen3("#{COMMAND} #{arguments}")
        flush(stdout)
      end #run

      private

      def flush(descriptor)
        puts descriptor.readlines
      end #flush

      def arguments
        ARGV.join(' ')
      end #arguments
    end # Echo
  end # Commands
end # Workman

Workman::Commands::Echo.new.run

