---

- name: Remote first connection
  hosts: 186.10.95.243
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
  #- setup: # aka gather_facts
  #  gather_facts: True
  # tasks:
  #   - name: Add SSH public key to user remote
  #     authorized_key:
  #       user: root
  #       #pass: "{{ lookup('env','HOST_PASS') }}"
  #       key: "{{ lookup('file', './files/workstation.pub') }}"

- name: Remote normal public key connection
  hosts: 186.10.95.243
  tasks:
    - include_vars: ./vars/romeo.yml
    - include: install-tasks.yml
