cartodb_errors:
  unknown_error:
    code: 0
    message: "We're sorry, an error has occurred"
    hint: "Please try again, or <a href='mailto:support@carto.com'>contact our support team</a> who will be happy to assist."
  empty_file:
    code: 1
    message: The file you have tried to upload has no data
    hint: "In order to create a table from importing a file, the file must have data"
  file_error:
    code: 2
    message: The file you are trying to upload has an invalid format
    hint: "Please note that supported formats are: CSV, XLS, SHP & ZIP"
  geometries_error:
    code: 3
    message: An error has occurred when importing geometry
    hint: ""
  url_error:
    code: 4
    message: An error has occurred when importing a URL
    hint: "Please note that supported formats are: CSV, XLS, SHP & ZIP"
  table_copy_error:
    code: 5
    message: Error while duplicating table
    hint: "Please try again, or <a href='mailto:support@carto.com'>contact our support team</a> who will be happy to assist."
  quota_error:
    code: 6
    message: Disk Quota Exceeded!
    hint: "Please remove some tables or upgrade your plan"
  invalid_interval:
    code: 7
    message: Invalid interval
    hint: "Sync interval must be at least 15 minutes"
