# encoding: UTF-8

require 'active_record'

module Carto
  class Notification

      MAP_LIKE_NOTIFICATION = 1
      SHARE_TABLE_NOTIFICATION = 2
      SHARE_VISUALIZATION_NOTIFICATION = 3
      UNSHARE_TABLE_NOTIFICATION = 4
      UNSHARE_VISUALIZATION_NOTIFICATION = 5
      DATA_IMPORT_FINISHED_NOTIFICATION = 6
      NOTIFICATIONS_TYPE = [
        MAP_LIKE_NOTIFICATION,
        SHARE_TABLE_NOTIFICATION,
        SHARE_VISUALIZATION_NOTIFICATION,
        UNSHARE_TABLE_NOTIFICATION,
        UNSHARE_VISUALIZATION_NOTIFICATION,
        DATA_IMPORT_FINISHED_NOTIFICATION
      ]

      def self.types
        return NOTIFICATIONS_TYPE
      end

  end
end
