steps:

# Cancel previous job on the same branch
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
  - '-c'
  - 'gcloud builds list --ongoing --filter="buildTriggerId=056221c7-f5ef-4857-9706-3bc1054799a3 AND substitutions.BRANCH_NAME=${BRANCH_NAME} AND id!=${BUILD_ID}" --format="get(ID)" > jobs_to_cancel'

- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
  - '-c'
  - 'gcloud builds cancel $(cat jobs_to_cancel | xargs) || true'

# Decrypt github key
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=script/ci/.id_github_cartofante.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=keyring-github-ci
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv script/ci/known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clean working directory
- name: alpine
  args: ['sh', '-c', 'rm -rf .* | true && rm -rf *']

# Checkout repo with submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args: ['-c', 'git clone git@github.com:CartoDB/cartodb -b "${BRANCH_NAME}" --depth 2 --recursive .']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Copy files to the right directories to run the tests
- name: ubuntu
  entrypoint: /bin/bash
  args:
    - -c
    - |
      cp private/script/ci/* .
      cp private/Dockerfile .
      cp -r private/build_resources/ .
      cp script/ci/* .
      cp config/app_config.yml.sample config/app_config.yml
      cp config/database.yml.sample config/database.yml
      cp lib/assets/javascripts/cdb/secrets.example.json lib/assets/javascripts/cdb/secrets.json

# Build image
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
    - -c
    - |
      docker pull gcr.io/cartodb-on-gcp-main-artifacts/builder-albertoh-test:latest
      docker build -t gcr.io/cartodb-on-gcp-main-artifacts/builder:current --cache-from gcr.io/cartodb-on-gcp-main-artifacts/builder-albertoh-test:latest .

# Run tests
- name: 'docker/compose:1.22.0'
  args: ['-f', 'docker-compose-pg11.yml', 'up', '--build', '-d']
  timeout: 900s

- name: gcr.io/cloud-builders/docker
  args: ['exec', '-i', 'builder_1', 'bash', '-c',
         'until pg_isready -h localhost -p 5432 -d template_postgis; do sleep 10 && echo "Waiting for postgres before starting the tests..." ; done' ]
  timeout: 120s 

- name: gcr.io/cloud-builders/docker
  args: ['exec', '-i', 'builder_1', 'bash', '-c', '/cartodb/runParallelTests.sh 24' ]
  timeout: 2700s

options:
    machineType: 'N1_HIGHCPU_32'
timeout: 3600s
