var _ = require('underscore');
var Backbone = require('backbone');

/**
 * Base layer object
 *
 * @constructor
 * @abstract
 * @memberof carto.layer
 * @api
 */
function Base () {
  this._id = Base.$generateId();
}

_.extend(Base.prototype, Backbone.Events);

/**
 * The instance id will be autogenerated by incrementing this variable.
 */
Base.$nextId = 0;

/**
 * Static funciton used internally to autogenerate source ids.
 */
Base.$generateId = function () {
  return 'L' + ++Base.$nextId;
};

module.exports = Base;
